[package]
name = "gpx"
description = "Rust read/write support for GPS Exchange Format (GPX)"
license = "MIT"
version = "0.8.1"
authors = ["Brendan Ashworth <brendan.ashworth@me.com>", "Corey Farwell <coreyf@rwell.org>", "Felix Gruber <felgru@gmx.de>"]
readme = "README.md"
documentation = "https://docs.rs/gpx"
repository = "https://github.com/georust/gpx"
edition = "2018"

[dependencies]
assert_approx_eq = "1.1.0"
chrono = "0.4.19"
error-chain = "0.12.4"
geo-types = "0.7.1"
xml-rs = "0.8.3"

[dev-dependencies]
geo = "0.17.1"
